### ISSUE TITLE
Feature: % of code coverage

### ISSUE THREAD

**Issue by damianoneill** [dave/courtney#8]
Hi Dave, thanks for Courtney.  

Quick question, is it possible to specify a % of code against the enforce command?  I'd like to use this option in an automated build, but I dont want to enforce 100% coverage.

**Comment by dave** [comment]
The problem with enforcing a percentage is that a change might add code coverage to one part but unintentionally remove it from another part, leaving the overall percentage the same.

The idea of this tool is that you can mark any sections you don't need to test with the `// notest` annotation, and make sure the rest is covered.

**Comment by dave** [comment]
I'm sure there's plenty of CI tools out there that can fail a build on a code coverage percentage, and `courtney` is just a pre-processor, so you can plug it's output into another tool...
